apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datarepo-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
data:
  nginxconf: |-
    worker_processes  auto;

    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;

      server { # simple reverse-proxy
        listen       {{ .Values.ui.nginxport }};

        # pass the status check through
        location /status {
            proxy_pass {{ .Values.ui.proxyPass.status }};
        }

        # pass the shutdown through, too
        location /shutdown {
            proxy_pass {{ .Values.ui.proxyPass.shutdown }};
        }

        # get swagger working
        location /swagger-ui.html {
            proxy_pass {{ .Values.ui.proxyPass.swagger }};
        }

        location ~ (configuration|ga4gh|webjars|api-docs|swagger-resources) {
            proxy_pass {{ .Values.ui.proxyPass.api }};
        }

        # serve static files
        location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html =404;
        }
      }
    }
