kind: Service
apiVersion: v1
metadata:
  name: {{ include "datarepo-ui.fullname" . }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  selector:
    component: {{ include "datarepo-ui.fullname" . }}
  type: {{ .Values.ui.service.type }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.port }}
