{{- if ne (index .Values.sqlproxy.cloudsql.instances 0).instance "instance" }}
{{- $hasCredentials := include "gcloud-sqlproxy.hasCredentials" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.sqlproxy.replicasCount }}
  selector:
    matchLabels:
      app: {{ include "gcloud-sqlproxy.fullname" . }}
  template:
    metadata:
      name: {{ include "gcloud-sqlproxy.fullname" . }}
      labels:
        app: {{ include "gcloud-sqlproxy.fullname" . }}
        app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.sqlproxy.podAnnotations | indent 8 }}
    spec:
      {{- if .Values.sqlproxy.rbac.create }}
      serviceAccountName: {{ include "gcloud-sqlproxy.fullname" . }}
      {{- end }}
      securityContext:
        runAsUser: 1002
        runAsGroup: 1002
        fsGroup: 1002
        runAsNonRoot: true
      containers:
      - name: sqlproxy
        image: "{{ .Values.sqlproxy.image }}:{{ .Values.sqlproxy.imageTag }}"
        imagePullPolicy: {{ default "" .Values.sqlproxy.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.sqlproxy.resources | indent 10 }}
        command:
        - /cloud_sql_proxy
        - --dir=/cloudsql
        - -instances={{- range .Values.sqlproxy.cloudsql.instances -}}
                        {{ .project }}:{{ .region }}:{{ .instance }}=tcp:0.0.0.0:{{ .port }},
                     {{- end }}
        {{ if $hasCredentials -}}
        - -credential_file=/secrets/cloudsql/{{ include "gcloud-sqlproxy.secretKey" . }}
        {{ end -}}
        {{- range $key, $value := .Values.sqlproxy.extraArgs }}
        - --{{ $key }}={{ $value }}
        {{- end }}
        {{- if .Values.sqlproxy.lifecycleHooks }}
        lifecycle:
{{ toYaml .Values.sqlproxy.lifecycleHooks | indent 10 }}
        {{- end }}
        ports:
        {{- range .Values.sqlproxy.cloudsql.instances }}
        - name: {{ .instanceShortName | default (.instance | trunc 15) | trimSuffix "-" }}
          containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
        {{ if $hasCredentials -}}
        - name: cloudsql-oauth-credentials
          mountPath: /secrets/cloudsql
        {{ end -}}
        - name: cloudsql
          mountPath: /cloudsql
      volumes:
      {{ if $hasCredentials -}}
      - name: cloudsql-oauth-credentials
        secret:
          secretName: {{ include "gcloud-sqlproxy.secretName" . }}
      {{ end -}}
      - name: cloudsql
        emptyDir: {}
      terminationGracePeriodSeconds: {{ .Values.sqlproxy.terminationGracePeriodSeconds }}
      nodeSelector:
{{ toYaml .Values.sqlproxy.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.sqlproxy.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.sqlproxy.tolerations | indent 8 }}
{{- end }}
