{{- if and .Values.sqlproxy.podDisruptionBudget (gt (.Values.sqlproxy.replicasCount | int) 1) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gcloud-sqlproxy.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ .Values.sqlproxy.podDisruptionBudget | indent 2 }}
{{- end -}}
