{{- if not .Values.sqlproxy.existingSecret -}}
{{- if not .Values.sqlproxy.usingGCPController -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  credentials.json: {{ .Values.sqlproxy.serviceAccountKey | b64enc | quote }}
{{- end -}}
{{- end -}}
