{{- if .Values.sqlproxy.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.sqlproxy.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-sqlproxy.name" . }}
    helm.sh/chart: {{ include "gcloud-sqlproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "gcloud-sqlproxy.fullname" . }}
  {{- if .Values.sqlproxy.googleServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.sqlproxy.googleServiceAccount | quote }}
  {{- end }}
{{- end }}
