{{- if .Values.oidc.ingress.domainName }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}
spec:
  domains:
    - {{ .Values.oidc.ingress.domainName }}
{{- end }}
