kind: Service
apiVersion: v1
metadata:
  name: {{ include "oidc-proxy.fullname" . }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}

  {{- if .Values.oidc.ingress.enabled }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"oidc-backend-config"}}'
  {{- end }}
spec:
  type: {{ .Values.oidc.service.type }}
  selector:
    component: {{ include "oidc-proxy.fullname" . }}
  ports:
  - protocol: TCP
    name: http
    port: {{ .Values.oidc.service.port }}
    targetPort: {{ .Values.oidc.service.port }}
