{{- if .Values.oidc.rbac.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ include "oidc-proxy.fullname" . }}-oidc-pod-running-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
    name: podsecuritypolicy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
{{- end }}
