{{- if .Values.oidc.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "oidc-proxy.fullname" . }}-oidc-use-pod-security-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-proxy.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "oidc-proxy.serviceAccountName" . }}
roleRef:
  kind: Role
  name: "{{ include "oidc-proxy.fullname" . }}-oidc-use-pod-security-policy-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
