{{- if .Values.api.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "datarepo-api.fullname" . }}-pod-k8s-access-role"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-api.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
{{- end }}
