{{- if .Values.api.rbac.create -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "datarepo-api.fullname" . }}-use-pod-security-policy"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-api.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "datarepo-api.serviceAccountName" . }}
roleRef:
  kind: Role
  name: "{{ include "datarepo-api.fullname" . }}-use-pod-security-policy-role"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
