{{- if not .Values.api.existingSecretDB -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datarepo-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datarepo-api.labels" . | nindent 4 }}
data:
  datarepo-password: {{ .Values.api.secretsgeneric.datarepoPassword | b64enc | quote }}
  stairway-password: {{ .Values.api.secretsgeneric.stairwayPassword | b64enc | quote }}
  credential-file-json: {{ .Values.api.secretsgeneric.serivceAccountCredentialFileJson | b64enc | quote }}
{{- end }}
