apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datarepo-ui.fullname" . }}
  labels:
    {{- include "datarepo-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: {{ include "datarepo-ui.fullname" . }}
  template:
    metadata:
      labels:
{{- include "datarepo-ui.labels" . | nindent 8 }}
        component: {{ include "datarepo-ui.fullname" . }}
##  dynamically populates environment annotations
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    spec:
      serviceAccountName: {{ include "datarepo-ui.serviceAccountName" . }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
      containers:
      - name: {{ .Chart.Name }}
        image: {{ if .Values.imageName }}{{ .Values.imageName }}{{ else }}"{{ .Values.image.repository }}:{{ .Values.image.tag }}"{{ end }}
        ports:
        - containerPort: {{ .Values.nginxport }}
##  dynamically populates environment variables
        env:
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /status
            port: {{ .Values.nginxport }}
          initialDelaySeconds: 35
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /status
            port: {{ .Values.nginxport }}
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
          - name: nginxconf
            mountPath: /etc/nginx/
      volumes:
        - name: nginxconf
          configMap:
            name: {{ include "datarepo-ui.fullname" . }}
            items:
              - key: nginxconf
                path: nginx.conf
{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 10 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
