ui:
  # Default values for datarepo-ui.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1

  image:
    repository: gcr.io/broad-jade-dev/jade-data-repo-ui
    tag: broad-jade-my_2020-02-14_15-04-11
    pullPolicy: IfNotPresent

  # nginx listen port for server
  nginxport: 8080

  proxyPass:
    status:   # http://api-service.data-repo:8080/status
    shutdown:   # http://api-service.data-repo:8080/shutdown
    swagger:  # http://api-service.data-repo:8080/swagger-ui.html
    api:  # http://api-service.data-repo:8080

  ## Extra environment variables that will be pass onto deployment pods
  env: {}

  ## Pod annotations
  podAnnotations: {}

  ## Node selectors and tolerations for server scheduling to nodes with taints
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  ##
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources: {}
  #  limits:
  #    cpu: 50m
  #    memory: 64Mi
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name:

  rbac:
    # Specifies whether a psp should be created
    create: true

  service:
    type: ClusterIP
    port: 8080
